// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOn-Xvl2fIqFGlIbLmv6pM76AMLC6BhdQ',
    appId: '1:509089469622:android:630ad59952bd26d46c8217',
    messagingSenderId: '509089469622',
    projectId: 'protein-tracker-68a13',
    databaseURL: 'https://protein-tracker-68a13-default-rtdb.firebaseio.com',
    storageBucket: 'protein-tracker-68a13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC58f7xnC3GCpzyo_A1ycSHGnUfsl_hkbE',
    appId: '1:509089469622:ios:bdc0a8a09e93aeac6c8217',
    messagingSenderId: '509089469622',
    projectId: 'protein-tracker-68a13',
    databaseURL: 'https://protein-tracker-68a13-default-rtdb.firebaseio.com',
    storageBucket: 'protein-tracker-68a13.appspot.com',
    androidClientId: '509089469622-bket5v9vdf17g173nqn8mvb93602vq70.apps.googleusercontent.com',
    iosClientId: '509089469622-qr7ddt193ecffqdmik6135669rqvlkrq.apps.googleusercontent.com',
    iosBundleId: 'com.zachsao.proteinTracker',
  );
}
